### ISSUE TITLE
RatingBar is not compatible with compose version 1.0.0-beta08

### ISSUE THREAD

**Issue by Vivecstel** [a914-gowtham/compose-ratingbar#7]
When using RatingBar library with compose version 1.0.0-beta08 I get the following runtime exception:

```
java.lang.NoSuchMethodError: No static method drawPath-3IgeMak$default(Landroidx/compose/ui/graphics/drawscope/DrawScope;Landroidx/compose/ui/graphics/Path;JFLandroidx/compose/ui/graphics/drawscope/DrawStyle;Landroidx/compose/ui/graphics/ColorFilter;Landroidx/compose/ui/graphics/BlendMode;ILjava/lang/Object;)V in class Landroidx/compose/ui/graphics/drawscope/DrawScope$DefaultImpls; or its super classes (declaration of 'androidx.compose.ui.graphics.drawscope.DrawScope$DefaultImpls' appears in /data/app/~~lPHkKeaVkTN6BDFdaohwwA==/com.steleot.jetpackcompose.playground-sSgRla-zZWCVDMLEPvKzFg==/base.apk)
        at com.gowtham.ratingbar.RatingStarKt$FilledStar$1$1.invoke(RatingStar.kt:43)
        at com.gowtham.ratingbar.RatingStarKt$FilledStar$1$1.invoke(RatingStar.kt:40)
        at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:101)
        at androidx.compose.ui.node.ModifiedDrawNode.performDraw(ModifiedDrawNode.kt:102)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:260)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:259)
...
```

Thanks

**Comment by a914-gowtham** [comment]
@Vivecstel Can you try this mavencentral dependency. I'am having issues with jitpack
`implementation 'io.github.a914-gowtham:compose-ratingbar:1.0.6'`

**Comment by Karim0x1** [comment]
It works for me, thank you

**Comment by Vivecstel** [comment]
I tested it also. Thanks @a914-gowtham for the quick update.

**Comment by sherazlinez** [comment]
Thanks, @a914-gowtham. It is working now
